version: "3.7"

services:
  db:
    image: mysql
    container_name: mysql-app-thymeleaf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: alunos

  app:
    image: maven:3.6.0-jdk-8
    container_name: app-thymeleaf
    volumes:
      - "../spring-boot-app-thymeleaf:/deploy"
    working_dir: "/deploy"
    ports:
      - "8080:8080"
    command: /bin/bash -c "mvn clean && mvn install && java -jar target/aula-spring-boot-1.0-SNAPSHOT.jar"
    links:
      - db